# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('users', '0004_auto_20170724_1844'),
	]

	operations = [
		migrations.RenameField(
			model_name='emailverifyrecord',
			old_name='sent_time',
			new_name='send_time',
		),
	]
